pin "application"
pin "@hotwired/stimulus", to: "vendor/stimulus.js"
pin "@hotwired/stimulus-loading", to: "vendor/stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "sortablejs", to: "vendor/sortablejs.js"
pin "chartkick", to: "vendor/chartkick.js"
pin "Chart.bundle", to: "vendor/chart.js"
